nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.4.0.cjs

npmScopes:
  qudak:
    npmRegistryServer: https://npm.pkg.github.com
    npmAuthToken: ${GITHUB_NORMAL_KEY}
    npmAlwaysAuth: true
